# Generated by Django 4.2.7 on 2023-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_material_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
